import { loadStoreConfig, type StoreConfig, type StoreConfigEnvironment } from "@/config/storeConfig";

const demoEnvironment: Required<StoreConfigEnvironment> = {
  MENDESK_STORE_ID: "demo-atelier",
  MENDESK_STORE_NAME: "Demo Atelier",
  MENDESK_STORE_SHORT_NAME: "Demo",
  MENDESK_STORE_LOGO_PATH: "/store/demo-atelier-mark.svg",
  MENDESK_STORE_PANEL_URL: "http://localhost:3000",
  MENDESK_STORE_REVIEW_URL: "",
  MENDESK_STORE_LOCALES: "en,es,uk",
  MENDESK_STORE_DEFAULT_LOCALE: "en",
  MENDESK_STORE_TIME_ZONE: "Europe/Dublin",
  MENDESK_STORE_CURRENCY: "EUR",
  MENDESK_STORE_CALLING_CODE: "353",
};

export function resolveStoreConfig(environment: StoreConfigEnvironment): StoreConfig {
  return loadStoreConfig({
    MENDESK_STORE_ID: environment.MENDESK_STORE_ID ?? demoEnvironment.MENDESK_STORE_ID,
    MENDESK_STORE_NAME: environment.MENDESK_STORE_NAME ?? demoEnvironment.MENDESK_STORE_NAME,
    MENDESK_STORE_SHORT_NAME: environment.MENDESK_STORE_SHORT_NAME ?? demoEnvironment.MENDESK_STORE_SHORT_NAME,
    MENDESK_STORE_LOGO_PATH: environment.MENDESK_STORE_LOGO_PATH ?? demoEnvironment.MENDESK_STORE_LOGO_PATH,
    MENDESK_STORE_PANEL_URL: environment.MENDESK_STORE_PANEL_URL ?? demoEnvironment.MENDESK_STORE_PANEL_URL,
    MENDESK_STORE_REVIEW_URL: environment.MENDESK_STORE_REVIEW_URL ?? demoEnvironment.MENDESK_STORE_REVIEW_URL,
    MENDESK_STORE_LOCALES: environment.MENDESK_STORE_LOCALES ?? demoEnvironment.MENDESK_STORE_LOCALES,
    MENDESK_STORE_DEFAULT_LOCALE: environment.MENDESK_STORE_DEFAULT_LOCALE ?? demoEnvironment.MENDESK_STORE_DEFAULT_LOCALE,
    MENDESK_STORE_TIME_ZONE: environment.MENDESK_STORE_TIME_ZONE ?? demoEnvironment.MENDESK_STORE_TIME_ZONE,
    MENDESK_STORE_CURRENCY: environment.MENDESK_STORE_CURRENCY ?? demoEnvironment.MENDESK_STORE_CURRENCY,
    MENDESK_STORE_CALLING_CODE: environment.MENDESK_STORE_CALLING_CODE ?? demoEnvironment.MENDESK_STORE_CALLING_CODE,
  });
}

export const storeConfig = resolveStoreConfig({
  MENDESK_STORE_ID: process.env.MENDESK_STORE_ID,
  MENDESK_STORE_NAME: process.env.MENDESK_STORE_NAME,
  MENDESK_STORE_SHORT_NAME: process.env.MENDESK_STORE_SHORT_NAME,
  MENDESK_STORE_LOGO_PATH: process.env.MENDESK_STORE_LOGO_PATH,
  MENDESK_STORE_PANEL_URL: process.env.MENDESK_STORE_PANEL_URL,
  MENDESK_STORE_REVIEW_URL: process.env.MENDESK_STORE_REVIEW_URL,
  MENDESK_STORE_LOCALES: process.env.MENDESK_STORE_LOCALES,
  MENDESK_STORE_DEFAULT_LOCALE: process.env.MENDESK_STORE_DEFAULT_LOCALE,
  MENDESK_STORE_TIME_ZONE: process.env.MENDESK_STORE_TIME_ZONE,
  MENDESK_STORE_CURRENCY: process.env.MENDESK_STORE_CURRENCY,
  MENDESK_STORE_CALLING_CODE: process.env.MENDESK_STORE_CALLING_CODE,
});
